name: Deploy production2

on:
  push:
    branches:
      - production2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut production2
        uses: actions/checkout@v4
        with:
          ref: production2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz  \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="node_modules" \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}

